package com.gymmanagement.notification;

public enum NotificationType {
    WORKOUT_ASSIGNED,
    DIET_UPDATED,
    SESSION_SCHEDULED,
    MEMBERSHIP_EXPIRY,
    INVOICE_CREATED,
    PAYMENT_RECEIVED,
    PARTIAL_PAYMENT_RECEIVED,
    BALANCE_PAYMENT_COMPLETED,
    PAYMENT_OVERDUE,
    MEMBERSHIP_RENEWED
}
